const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const N = require('../apps-script/NexusMorning.js');
const clone = x => JSON.parse(JSON.stringify(x));
const NOW = '2026-09-24T06:00:00+09:00';
const config = () => ({timezone:'Asia/Tokyo',recipient:'owner@example.test',recipient_allowlist:['owner@example.test'],read_scope_confirmed:true,display_scope_confirmed:true,production_approved:true,send_enabled:true,test_send_approved:true,nexus_version:2,morning_hour:6,morning_minute:0});
const view = () => ({schema:1,surface:'morning',state:'ok',local_date:'2026-09-24',hours_date:'2026-09-24',as_of:NOW,expires_at:'2026-09-24T06:15:00+09:00',complete:true,snapshot:'a'.repeat(40),hours_status:'reported',hours_text:'今日の勤務：09:30〜18:00',hours_records:[],calendar_status:'current',calendar_message:'取得済み',events:[],focus:null,actions:[],alerts:[],projects:[],limitation:'登録された共有範囲です。'});
function env(c=config()) {
  const records=new Map(), mails=[]; let unlocked=0;
  const e={lock:()=>true,unlock:()=>unlocked++,config:()=>clone(c),now:()=>NOW,key:x=>'TM_SEND_'+crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),get:k=>records.has(k)?clone(records.get(k)):null,put:(k,v)=>records.set(k,clone(v)),bytes:s=>Buffer.byteLength(s),quota:()=>10,current:()=>({current:true}),mail:m=>mails.push(m)};
  return {e,records,mails,unlocked:()=>unlocked};
}
function gas(files=['App.gs','Migration.gs'], initial={}) {
  const props={TM_CONFIG:JSON.stringify(config()),...initial}; const triggers=[{getHandlerFunction:()=> 'runMorning'},{getHandlerFunction:()=> 'unrelated'}],requests=[],mails=[];
  let held=false, now=Date.parse(NOW); const RealDate=Date;
  class FakeDate extends RealDate {constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}}
  const context={NexusMorning:N,Date:FakeDate,console:{log:()=>{}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]??null,setProperty:(k,v)=>{props[k]=v;},getProperties:()=>({...props}),setProperties:o=>Object.assign(props,o)})},LockService:{getScriptLock:()=>({tryLock:()=>{if(held)return false;held=true;return true;},releaseLock:()=>{held=false;}})},Utilities:{newBlob:s=>({getBytes:()=>[...Buffer.from(s)]}),getUuid:()=> 'fixed-id',DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()].map(x=>x>127?x-256:x)},ScriptApp:{getOAuthToken:()=> 'opaque-test-token',getProjectTriggers:()=>triggers.slice(),deleteTrigger:t=>triggers.splice(triggers.indexOf(t),1)},MailApp:{getRemainingDailyQuota:()=>10,sendEmail:m=>mails.push(m)},UrlFetchApp:{fetch:(url,options)=>{requests.push({url,options});throw Error('offline');}}};
  vm.createContext(context);for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,'apps-script',f),'utf8'),context,{filename:f});
  return {context,props,triggers,requests,mails,setNow:t=>{now=Date.parse(t);},locked:()=>held};
}
test('ledger key is byte-compatible with the actual preserved production original',()=>{
  const g=gas();const original=fs.readFileSync(path.join(__dirname,'fixtures/morning-legacy-key.js'),'utf8');
  vm.runInContext(original,g.context,{filename:'morning-legacy-key.js'});
  for(const kind of ['morning','test']){const parts=['2026-09-24','owner@example.test',kind];assert.equal(g.context.nexusKey_(parts),g.context.tmKey_(parts));}
});
for(const state of ['SENT','SENDING','UNKNOWN'])test('existing '+state+' record prevents same-day resend',()=>{
  const c=config(),x=env(c);x.records.set(x.e.key(['2026-09-24',c.recipient,'morning']),{state,date:'2026-09-24',kind:'morning'});
  assert.equal(N.send(c,view(),'morning',x.e).duplicate_prevented,true);assert.equal(x.mails.length,0);assert.equal(x.unlocked(),1);
});
test('normal send persists SENT, preserves receipt uncertainty and will not send twice',()=>{const c=config(),x=env(c);assert.equal(N.send(c,view(),'morning',x.e).receipt_verified,false);N.send(c,view(),'morning',x.e);assert.equal(x.mails.length,1);});
test('ambiguous MailApp failure persists UNKNOWN and never auto-retries',()=>{const c=config(),x=env(c);let attempts=0;x.e.mail=()=>{attempts++;throw Error('timeout');};assert.throws(()=>N.send(c,view(),'morning',x.e),/SEND_UNKNOWN/);assert.equal(N.send(c,view(),'morning',x.e).state,'UNKNOWN');assert.equal(attempts,1);});
test('SENDING remains a retry barrier when recording UNKNOWN also fails',()=>{const c=config(),x=env(c),put=x.e.put;x.e.mail=()=>{throw Error('ambiguous');};x.e.put=(k,v)=>{if(v.state==='UNKNOWN')throw Error('storage');put(k,v);};assert.throws(()=>N.send(c,view(),'morning',x.e),/SEND_UNKNOWN/);assert.equal(N.send(c,view(),'morning',x.e).state,'SENDING');});
test('stop during source retrieval wins at the shared-lock config reread',()=>{const c=config(),x=env(c);x.e.config=()=>({...c,send_enabled:false});assert.throws(()=>N.send(c,view(),'morning',x.e),/CONFIG_CHANGED/);assert.equal(x.mails.length,0);assert.equal(x.records.size,0);assert.equal(x.unlocked(),1);});
test('busy lock and disabled configuration cannot send',()=>{const c=config(),x=env(c);x.e.lock=()=>false;assert.throws(()=>N.send(c,view(),'morning',x.e),/BUSY/);assert.equal(x.unlocked(),0);assert.equal(N.send({...c,send_enabled:false},view(),'morning',x.e).state,'DISABLED');assert.equal(x.mails.length,0);});
for(const [label,patch] of [['expired',{expires_at:NOW}],['old',{as_of:'2026-09-24T05:44:59+09:00'}],['future',{as_of:'2026-09-24T06:01:01+09:00'}],['wrong day',{local_date:'2026-09-23'}],['incomplete',{complete:false}]])test('rejects '+label+' data before sending',()=>{const c=config(),x=env(c);assert.throws(()=>N.send(c,{...view(),...patch},'morning',x.e));assert.equal(x.mails.length,0);});
test('revalidates the day after checking canonical source head',()=>{const c=config(),x=env(c);x.e.current=()=>{x.e.now=()=> '2026-09-25T00:00:00+09:00';return {current:true};};assert.throws(()=>N.send(c,view(),'morning',x.e),/INVALID_VIEW/);assert.equal(x.records.size,0);});
test('changed canonical head rejects delivery without recording send intent',()=>{const c=config(),x=env(c);x.e.current=()=>({current:false});assert.throws(()=>N.send(c,view(),'morning',x.e),/SOURCE_CHANGED/);assert.equal(x.records.size,0);});
test('migration test is globally single-attempt, even on another date',()=>{const c=config(),x=env(c);N.send(c,view(),'test',x.e);x.e.now=()=> '2026-09-25T06:00:00+09:00';const v={...view(),local_date:'2026-09-25',hours_date:'2026-09-25',as_of:x.e.now(),expires_at:'2026-09-25T06:15:00+09:00'};assert.throws(()=>N.send(c,v,'test',x.e),/TEST_ALREADY_ATTEMPTED/);assert.equal(x.mails.length,1);});
test('migration test ambiguous result permanently consumes its one-attempt marker',()=>{const c=config(),x=env(c);x.e.mail=()=>{throw Error('timeout');};assert.throws(()=>N.send(c,view(),'test',x.e),/SEND_UNKNOWN/);assert.equal(x.records.get('NEXUS_MIGRATION_TEST').state,'SENDING');});
test('all alerts, general appointments, all-day events and HTML escapes survive rendering',()=>{const v=view();v.hours_text='<script>&"';v.alerts=Array.from({length:7},(_,i)=>({title:'注意'+i,text:'<b>&'+i}));v.events=[{title:'面談 <x>',start:'2026-09-24T10:00:00+09:00',end:'2026-09-24T11:00:00+09:00',all_day:false},{title:'記念日',all_day:true}];const m=N.render(v);for(let i=0;i<7;i++)assert.ok(m.text.includes('注意'+i));assert.ok(m.text.includes('09-24 10:00〜09-24 11:00 面談 <x>'));assert.ok(m.text.includes('終日 記念日'));assert.ok(m.html.includes('&lt;script&gt;&amp;&quot;'));assert.ok(!m.html.includes('<b>'));});
test('morning outage sends explicit unavailable content; test outage sends nothing',()=>{const g=gas();const r=g.context.runMorning();assert.equal(r.state,'SENT');assert.ok(g.mails[0].subject.includes('情報取得できず'));assert.ok(g.mails[0].body.includes('勤務時間未取得'));assert.equal(g.requests.filter(x=>x.url.includes('/daily/refresh')).length,0);assert.throws(()=>g.context.sendTestMorning(),/CALENDAR_NETWORK_UNAVAILABLE/);assert.equal(g.mails.length,1);});
test('unavailable view cannot smuggle stale work or event data',()=>{for(const patch of [{focus:{title:'old'}},{events:[{}]},{actions:[{}]},{hours_records:[{}]},{snapshot:'a'.repeat(40)}])assert.throws(()=>N.validate({...N.unavailable(NOW),...patch},NOW),/INVALID_UNAVAILABLE/);});
const event = (id,extra={})=>({id,status:'confirmed',summary:'09:30-18:00',start:{dateTime:'2026-09-24T09:30:00+09:00'},end:{dateTime:'2026-09-24T18:00:00+09:00'},...extra});
test('Calendar follows every page, keeps description-only explicit shift, and limits source scope',()=>{const calls=[];const p=N.calendar((id,q)=>{calls.push({id,q});return {kind:'calendar#events',items:[event(id+(q.pageToken||'first'),{description:'10月度シフト'})],...(!q.pageToken?{nextPageToken:'two'}:{})};},['main','work'],'work',NOW,'req');assert.equal(calls.length,4);assert.ok(calls.every(x=>x.q.timeMin==='2026-09-24T00:00:00+09:00'&&x.q.timeMax==='2026-09-26T00:00:00+09:00'));assert.ok(!calls[0].q.fields.includes('description'));assert.ok(calls[2].q.fields.includes('description'));assert.equal(p.calendars[0].events[0].shift_evidence,undefined);assert.equal(p.calendars[1].events[0].shift_evidence,'10月度シフト');});
test('time-like titles without explicit shift evidence do not become work hours',()=>{const p=N.calendar(()=>({kind:'calendar#events',items:[event('time'),event('all',{summary:'シフト',start:{date:'2026-09-24'},end:{date:'2026-09-25'}})]}),['work'],'work',NOW,'req');assert.ok(p.calendars[0].events.every(e=>!e.shift_evidence));});
test('cancelled and self-declined Calendar events are excluded',()=>{const p=N.calendar(()=>({kind:'calendar#events',items:[event('cancel',{status:'cancelled'}),event('decline',{attendees:[{self:true,responseStatus:'declined'}]}),event('keep')]}),['work'],'work',NOW,'req');assert.deepEqual(p.calendars[0].events.map(e=>e.id),['keep']);});
test('any Calendar page failure prevents the refresh write',()=>{const g=gas();let pages=0;g.context.nexusCalendarGet_=()=>{pages++;if(pages===2)throw Error('page failure');return {kind:'calendar#events',items:[],nextPageToken:'next'};};let writes=0;g.context.nexusPost_=()=>{writes++;};assert.throws(()=>g.context.nexusRefresh_(),/page failure/);assert.equal(writes,0);});
test('Calendar cursor cycles and missing time zones are rejected',()=>{assert.throws(()=>N.calendar(()=>({kind:'calendar#events',items:[],nextPageToken:'loop'}),['work'],'work',NOW,'req'),/INVALID_PAGINATION/);assert.throws(()=>N.calendar(()=>({kind:'calendar#events',items:[event('bad',{start:{dateTime:'2026-09-24T09:30:00'},end:{dateTime:'2026-09-24T18:00:00'}})]}),['work'],'work',NOW,'req'),/INVALID_EVENT_TIMEZONE/);});
test('GAS adapter refuses calendars outside the fixed two-source allowlist',()=>{const g=gas();assert.throws(()=>g.context.nexusCalendarGet_('unrelated',{}),/CALENDAR_NOT_ALLOWED/);assert.equal(g.requests.length,0);});
test('migration backup preserves exact original config and all original ledger bytes',()=>{const original=JSON.stringify({...config(),nexus_version:undefined});const ledger=JSON.stringify({state:'UNKNOWN',date:'2026-09-23',kind:'morning'});const g=gas(['Migration.gs'],{TM_CONFIG:original,TM_SEND_old:ledger,OTHER:'keep'});g.context.backupAndStopLegacyMorning();const meta=JSON.parse(g.props.NEXUS_LEGACY_BACKUP_META);let raw='';for(let i=0;i<meta.chunks;i++)raw+=g.props['NEXUS_LEGACY_BACKUP_'+i];assert.deepEqual(JSON.parse(raw),{TM_CONFIG:original,TM_SEND_old:ledger});assert.equal(g.props.TM_SEND_old,ledger);assert.equal(g.props.OTHER,'keep');assert.equal(JSON.parse(g.props.TM_CONFIG).send_enabled,false);assert.deepEqual(g.triggers.map(t=>t.getHandlerFunction()),['unrelated']);const chunks=raw;g.context.backupAndStopLegacyMorning();let again='';for(let i=0;i<meta.chunks;i++)again+=g.props['NEXUS_LEGACY_BACKUP_'+i];assert.equal(again,chunks);assert.equal(g.locked(),false);});
test('failed first backup verification leaves original config and triggers active',()=>{const g=gas(['Migration.gs']);const original=g.props.TM_CONFIG;const svc=g.context.PropertiesService.getScriptProperties;g.context.PropertiesService.getScriptProperties=()=>({...svc(),setProperties:()=>{}});assert.throws(()=>g.context.backupAndStopLegacyMorning(),/BACKUP_VERIFY_FAILED/);assert.equal(g.props.TM_CONFIG,original);assert.ok(g.triggers.some(t=>t.getHandlerFunction()==='runMorning'));});
test('existing backup must be verified before reporting it usable and stopping legacy',()=>{const g=gas(['Migration.gs'],{NEXUS_LEGACY_BACKUP_META:JSON.stringify({chunks:1}),NEXUS_LEGACY_BACKUP_0:'corrupt'});assert.throws(()=>g.context.backupAndStopLegacyMorning(),/BACKUP/);});
test('sent mail with failed final ledger persistence remains UNKNOWN and blocks retry',()=>{const c=config(),x=env(c),put=x.e.put;x.e.put=(k,v)=>{if(v.state==='SENT')throw Error('storage failed after mail');put(k,v);};assert.throws(()=>N.send(c,view(),'morning',x.e),/SEND_UNKNOWN/);assert.equal(x.mails.length,1);assert.equal(N.send(c,view(),'morning',x.e).state,'UNKNOWN');assert.equal(x.mails.length,1);});
test('quota and oversize alerts fail before sending without dropping any alert',()=>{const c=config(),x=env(c);x.e.quota=()=>0;assert.throws(()=>N.send(c,view(),'morning',x.e),/MAIL_QUOTA/);assert.equal(x.records.size,0);x.e.quota=()=>10;const v=view();v.alerts=[{title:'長い注意',text:'x'.repeat(180000)}];assert.throws(()=>N.send(c,v,'morning',x.e),/MAIL_TOO_LARGE/);assert.equal(v.alerts[0].text.length,180000);assert.equal(x.mails.length,0);});
test('source verification transport failure does not send or create a misleading ledger record',()=>{const c=config(),x=env(c);x.e.current=()=>{throw Error('network');};assert.throws(()=>N.send(c,view(),'morning',x.e),/network/);assert.equal(x.mails.length,0);assert.equal(x.records.size,0);assert.equal(x.unlocked(),1);});
test('Calendar limits reject an oversized result instead of silently using a partial snapshot',()=>{assert.throws(()=>N.calendar(()=>({kind:'calendar#events',items:Array.from({length:51},(_,i)=>event('item'+i))}),['work'],'work',NOW,'req'),/CALENDAR_EVENT_LIMIT/);});
test('stopMorning preserves ledger and unrelated triggers while disabling test and morning sends',()=>{const g=gas(['App.gs'],{TM_SEND_keep:'{"state":"SENT"}'});g.context.stopMorning();const c=JSON.parse(g.props.TM_CONFIG);assert.equal(c.send_enabled,false);assert.equal(c.test_send_approved,false);assert.equal(g.props.TM_SEND_keep,'{"state":"SENT"}');assert.deepEqual(g.triggers.map(t=>t.getHandlerFunction()),['unrelated']);assert.equal(g.locked(),false);});
test('failed morning-trigger install rolls back only newly created sync trigger',()=>{const g=gas(['App.gs']);g.triggers.splice(0,1);const c=JSON.parse(g.props.TM_CONFIG);c.nexus_receipt_confirmed=true;g.props.TM_CONFIG=JSON.stringify(c);g.context.ScriptApp.newTrigger=name=>{const chain={};for(const k of ['timeBased','everyHours','everyDays','atHour','nearMinute','inTimezone'])chain[k]=()=>chain;chain.create=()=>{if(name==='runMorning')throw Error('trigger API failed');g.triggers.push({getHandlerFunction:()=>name});};return chain;};assert.throws(()=>g.context.installNexusTriggers(),/trigger API failed/);assert.deepEqual(g.triggers.map(t=>t.getHandlerFunction()),['unrelated']);assert.equal(g.locked(),false);});
test('only standalone shift labels qualify; shift meetings, negations and unrelated descriptions do not',()=>{const labels=['シフト','10月度シフト',' 9月 シフト ','シフト会議','シフト未定','シフトではない','シフトの相談'];const p=N.calendar(()=>({kind:'calendar#events',items:labels.map((description,i)=>event('case'+i,{description}))}),['work'],'work',NOW,'req');assert.deepEqual(p.calendars[0].events.map(e=>!!e.shift_evidence),[true,true,true,false,false,false,false]);});
test('actual Calendar HTML paragraphs preserve explicit shift evidence without forwarding descriptions',()=>{
  const labels=['<p>10月度シフト</p>','<div>シフト</div>','private note<br>10月度シフト<br>other note','<p><strong>10月度</strong><span>シフト</span></p>','<p>&nbsp;10月度シフト&#160;</p>'];
  const p=N.calendar(()=>({kind:'calendar#events',items:labels.map((description,i)=>event('html'+i,{description}))}),['work','main'],'work',NOW,'req');
  assert.deepEqual(p.calendars[0].events.map(e=>e.shift_evidence),['10月度シフト','シフト','10月度シフト','10月度シフト','10月度シフト']);
  assert.ok(p.calendars[1].events.every(e=>!e.shift_evidence));
  assert.ok(p.calendars.every(c=>c.events.every(e=>!Object.hasOwn(e,'description'))));
  assert.ok(!JSON.stringify(p).includes('private note'));assert.ok(!JSON.stringify(p).includes('<p>'));
});
test('HTML inline markup cannot turn shift meetings, negations or hidden markup into shift evidence',()=>{
  const labels=['<p>シフト会議</p>','<p>シフト未定</p>','<p>シフトではない</p>','<p><b>シフト</b>会議</p>','<p>シフト<span>ではない</span></p>','<p>相談：<b>シフト</b></p>','<script>シフト</script>','<style>シフト</style>','<!-- シフト -->','<p>10月度シフトではない</p>'];
  const p=N.calendar(()=>({kind:'calendar#events',items:labels.map((description,i)=>event('notshift'+i,{description}))}),['work'],'work',NOW,'req');
  assert.ok(p.calendars[0].events.every(e=>!e.shift_evidence));
});
function successfulGas() {
  const g=gas(['App.gs'],{NEXUS_DAILY_TOKEN:'t'.repeat(48)}),calls=[];
  g.context.UrlFetchApp.fetch=(url,options)=>{calls.push({url,options});const payload=options.payload&&JSON.parse(options.payload);let body;
    if(url.startsWith('https://www.googleapis.com/calendar/')) body={kind:'calendar#events',items:[event(url.includes('c73j0')?'shift':'meeting',{summary:url.includes('c73j0')?'勤務':'面談',description:'10月度シフト'})]};
    else if(url.endsWith('/daily/refresh')) {assert.deepEqual(Object.keys(payload).sort(),['calendars','complete','range_end','range_start','request_id','retrieved_at']);assert.equal(payload.calendars.length,2);assert.equal(payload.complete,true);body={view:view()};}
    else if(url.endsWith('/daily/check')) {assert.deepEqual(Object.keys(payload).sort(),['as_of','local_date','snapshot']);assert.equal(payload.snapshot,'a'.repeat(40));body={current:true};}
    else throw Error('unexpected route');return {getResponseCode:()=>200,getContentText:()=>JSON.stringify(body)};
  };return {...g,calls};
}
test('deployment adapter refresh sends strict payload, checks source, and persists original-compatible SENT key',()=>{const g=successfulGas();const r=g.context.runMorning();assert.equal(r.state,'SENT');assert.equal(g.mails.length,1);assert.equal(g.calls.length,4);assert.ok(g.calls.every(x=>x.options.followRedirects===false));assert.ok(g.calls.filter(x=>x.url.includes('/daily/')).every(x=>x.options.headers.Authorization==='Bearer '+'t'.repeat(48)));const key=g.context.nexusKey_(['2026-09-24','owner@example.test','morning']);assert.equal(JSON.parse(g.props[key]).state,'SENT');g.context.runMorning();assert.equal(g.mails.length,1);});
test('deployment preview does not send; authorized migration test sends once and remains independent of morning ledger',()=>{const g=successfulGas();g.context.previewMorning();assert.equal(g.mails.length,0);assert.equal(JSON.parse(g.props.NEXUS_PREVIEW).snapshot,'a'.repeat(40));g.context.authorizeMigrationTest();assert.equal(g.context.sendTestMorning().state,'SENT');assert.equal(g.mails.length,1);assert.ok(g.mails[0].subject.startsWith('［テスト］'));assert.equal(JSON.parse(g.props.NEXUS_MIGRATION_TEST).state,'SENT');assert.throws(()=>g.context.authorizeMigrationTest(),/TEST_ALREADY_ATTEMPTED/);assert.equal(g.context.sendTestMorning().duplicate_prevented,true);assert.equal(g.context.runMorning().state,'SENT');assert.equal(g.mails.length,2);});
test('deployment strict route, missing token, response errors and invalid JSON fail before content use',()=>{const g=successfulGas();assert.throws(()=>g.context.nexusPost_('/mcp',{}),/INVALID_OPERATION/);delete g.props.NEXUS_DAILY_TOKEN;assert.throws(()=>g.context.nexusPost_('/daily/read',{}),/LIMITED_CONNECTION_REQUIRED/);g.props.NEXUS_DAILY_TOKEN='t'.repeat(48);g.context.UrlFetchApp.fetch=()=>({getResponseCode:()=>302,getContentText:()=>JSON.stringify(view())});assert.throws(()=>g.context.nexusPost_('/daily/read',{}),/NEXUS_REQUEST_FAILED/);g.context.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>'<html>login</html>'});assert.throws(()=>g.context.nexusPost_('/daily/read',{}),/INVALID_NEXUS_RESPONSE/);});
test('migration backup checksum catches valid JSON tampering before a second stop',()=>{const g=gas(['Migration.gs']);g.context.backupAndStopLegacyMorning();const changed=JSON.parse(g.props.NEXUS_LEGACY_BACKUP_0);changed.TM_CONFIG=JSON.stringify({...config(),recipient:'different@example.test'});g.props.NEXUS_LEGACY_BACKUP_0=JSON.stringify(changed);assert.throws(()=>g.context.backupAndStopLegacyMorning(),/BACKUP_VERIFY_FAILED/);});
